version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/base"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/open-code"
    schedule:
      interval: "weekly"
